//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortAble.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortAble.Properties.LangStrings", typeof(LangStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App successfully downloaded!.
        /// </summary>
        public static string AppDownloadedMsg {
            get {
                return ResourceManager.GetString("AppDownloadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems installing the following app:
        ///
        ///{0}
        ///
        ///This could be due an incomplete download or other network issue..
        /// </summary>
        public static string AppDownloadErrorMsg {
            get {
                return ResourceManager.GetString("AppDownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that an IPv4 connection is required to download resources from &apos;{0}&apos;..
        /// </summary>
        public static string AppInternetProtocolWarningMsg {
            get {
                return ResourceManager.GetString("AppInternetProtocolWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps successfully downloaded!.
        /// </summary>
        public static string AppsDownloadedMsg {
            get {
                return ResourceManager.GetString("AppsDownloadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems installing the following apps:
        ///
        ///{0}
        ///
        ///This could be due an incomplete download or other network issue..
        /// </summary>
        public static string AppsDownloadErrorMsg {
            get {
                return ResourceManager.GetString("AppsDownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps successfully updated!.
        /// </summary>
        public static string AppsUpdatedMsg {
            get {
                return ResourceManager.GetString("AppsUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} update is available. Would you like to update now?.
        /// </summary>
        public static string AppUpdateAvailableMsg {
            get {
                return ResourceManager.GetString("AppUpdateAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App successfully updated!.
        /// </summary>
        public static string AppUpdatedMsg {
            get {
                return ResourceManager.GetString("AppUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updates are available. Would you like to update now?.
        /// </summary>
        public static string AppUpdatesAvailableMsg {
            get {
                return ResourceManager.GetString("AppUpdatesAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSureMsg {
            get {
                return ResourceManager.GetString("AreYouSureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you always want to open this kind of file with this application?.
        /// </summary>
        public static string AssociateQuestionMsg0 {
            get {
                return ResourceManager.GetString("AssociateQuestionMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you always want to open the following file types with this application?
        ///
        ///Types: {0}.
        /// </summary>
        public static string AssociateQuestionMsg1 {
            get {
                return ResourceManager.GetString("AssociateQuestionMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the checksum of the following file:
        ///
        ///{0}
        ///
        ///In some cases, it&apos;s just a little synchronization problem in the online database. However, this could also be due to an incomplete download or other issue..
        /// </summary>
        public static string ChecksumErrorMsg {
            get {
                return ResourceManager.GetString("ChecksumErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server &apos;{0}&apos; was added but the configuration file could not be verified..
        /// </summary>
        public static string CustomAppSupplierInvalidMsg {
            get {
                return ResourceManager.GetString("CustomAppSupplierInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App servers have been updated.
        ///
        ///Please note that these changes may not take effect until you restart this application..
        /// </summary>
        public static string CustomAppSupplierUpdatedMsg {
            get {
                return ResourceManager.GetString("CustomAppSupplierUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is being accessed . . ..
        /// </summary>
        public static string DatabaseAccessMsg {
            get {
                return ResourceManager.GetString("DatabaseAccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to retry?.
        /// </summary>
        public static string DownloadRetryMsg {
            get {
                return ResourceManager.GetString("DownloadRetryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}/{1}.
        /// </summary>
        public static string FileCountStatus {
            get {
                return ResourceManager.GetString("FileCountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following process must be closed:
        ///
        ///{0}
        ///
        ///Please make sure your settings are saved before confirming this message!.
        /// </summary>
        public static string FileLockMsg {
            get {
                return ResourceManager.GetString("FileLockMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following processes must be closed:
        ///
        ///{0}
        ///
        ///Please make sure your settings are saved before confirming this message!.
        /// </summary>
        public static string FileLocksMsg {
            get {
                return ResourceManager.GetString("FileLocksMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Not available . . . ].
        /// </summary>
        public static string HostNotAvailable {
            get {
                return ResourceManager.GetString("HostNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing, please wait . . ..
        /// </summary>
        public static string InitializingMsg {
            get {
                return ResourceManager.GetString("InitializingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing, please wait....
        /// </summary>
        public static string InitStatusText {
            get {
                return ResourceManager.GetString("InitStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} installation skipped!.
        /// </summary>
        public static string InstallSkippedMsg {
            get {
                return ResourceManager.GetString("InstallSkippedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is no internet connection available..
        /// </summary>
        public static string InternetIsNotAvailableMsg {
            get {
                return ResourceManager.GetString("InternetIsNotAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IPv4 connection could not be established on your system. This can lead to unwanted problems..
        /// </summary>
        public static string InternetProtocolWarningMsg {
            get {
                return ResourceManager.GetString("InternetProtocolWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No app data found..
        /// </summary>
        public static string NoAppDataFound {
            get {
                return ResourceManager.GetString("NoAppDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No apps available..
        /// </summary>
        public static string NoAppsFound {
            get {
                return ResourceManager.GetString("NoAppsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No large app image found..
        /// </summary>
        public static string NoLargeAppImagesFound {
            get {
                return ResourceManager.GetString("NoLargeAppImagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there are currently no download servers available.
        ///Please try again later..
        /// </summary>
        public static string NoServerAvailableMsg {
            get {
                return ResourceManager.GetString("NoServerAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No small app image found..
        /// </summary>
        public static string NoSmallAppImagesFound {
            get {
                return ResourceManager.GetString("NoSmallAppImagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough free space on the storage device ({0}:\).
        ///
        ///You must free up at least {1} more space..
        /// </summary>
        public static string NotEnoughSpaceMsg {
            get {
                return ResourceManager.GetString("NotEnoughSpaceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available..
        /// </summary>
        public static string NoUpdatesFound {
            get {
                return ResourceManager.GetString("NoUpdatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This directory requires elevated user permissions to write..
        /// </summary>
        public static string NoWritePermissionsMsg {
            get {
                return ResourceManager.GetString("NoWritePermissionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled..
        /// </summary>
        public static string OperationCanceledMsg {
            get {
                return ResourceManager.GetString("OperationCanceledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed..
        /// </summary>
        public static string OperationCompletedMsg {
            get {
                return ResourceManager.GetString("OperationCompletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        public static string OperationFailedMsg {
            get {
                return ResourceManager.GetString("OperationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is incomplete. Would you like to download it again?.
        /// </summary>
        public static string RequirementsErrorMsg {
            get {
                return ResourceManager.GetString("RequirementsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can add more app providers so you can also download and receive updates from others who want to share their apps.
        ///
        ///However, please note that login credentials are not secure and can be easily read if someone has access to the hard drive on which this apps suite resides.
        ///
        ///I&apos;m open to adding advanced security features if more users want it.
        ///
        ///Please check out the GitHub repository and create an issue with your request, or visit Si13n7.com and write a support ticket..
        /// </summary>
        public static string SourceManagerWarnMsg {
            get {
                return ResourceManager.GetString("SourceManagerWarnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom transfer directory can not be on the same storage device as the suite..
        /// </summary>
        public static string TransferDirMsg {
            get {
                return ResourceManager.GetString("TransferDirMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck.
        /// </summary>
        public static string Uncheck {
            get {
                return ResourceManager.GetString("Uncheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update canceled..
        /// </summary>
        public static string UpdateCanceled {
            get {
                return ResourceManager.GetString("UpdateCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
