//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsLauncher.LangResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsLauncher.LangResources.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über Port-Able.
        /// </summary>
        internal static string AboutForm {
            get {
                return ResourceManager.GetString("AboutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port-Able wird entwickelt und gestaltet von {0}, gegründet und
        ///aktiv betrieben von Roy Schrödel.
        ///
        ///Lust einen Beitrag zu leisten? {1} oder {2}!
        ///Verbesserungsvorschläge sind auch sehr willkommen!.
        /// </summary>
        internal static string aboutInfoLabel {
            get {
                return ResourceManager.GetString("aboutInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spende mit PayPal.
        /// </summary>
        internal static string aboutInfoLabelLinkLabel1 {
            get {
                return ResourceManager.GetString("aboutInfoLabelLinkLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to melde ein Problem.
        /// </summary>
        internal static string aboutInfoLabelLinkLabel2 {
            get {
                return ResourceManager.GetString("aboutInfoLabelLinkLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startargumente hinzufügen:.
        /// </summary>
        internal static string addArgsLabel {
            get {
                return ResourceManager.GetString("addArgsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu aktuellen Befehlszeilenargumente hinzufügen..
        /// </summary>
        internal static string addArgsLabelTip {
            get {
                return ResourceManager.GetString("addArgsLabelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Apps hinzufügen..
        /// </summary>
        internal static string addBtnTip {
            get {
                return ResourceManager.GetString("addBtnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In die Shell aufnehmen.
        /// </summary>
        internal static string addToShellBtn {
            get {
                return ResourceManager.GetString("addToShellBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App-Ordner:.
        /// </summary>
        internal static string appDirsLabel {
            get {
                return ResourceManager.GetString("appDirsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Verzeichnisse, die Portable Apps enthalten, hinzufügen:
        ///
        ///- Vollständiges Verzeichnis angeben
        ///- Ein Verzeichnis pro Zeile
        ///- Umgebungsvariablen werden akzeptiert.
        /// </summary>
        internal static string appDirsTip {
            get {
                return ResourceManager.GetString("appDirsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausführen.
        /// </summary>
        internal static string appMenuItem1 {
            get {
                return ResourceManager.GetString("appMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Administrator ausführen.
        /// </summary>
        internal static string appMenuItem2 {
            get {
                return ResourceManager.GetString("appMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App-Pfad öffnen.
        /// </summary>
        internal static string appMenuItem3 {
            get {
                return ResourceManager.GetString("appMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktopverknüpfung erstellen.
        /// </summary>
        internal static string appMenuItem4 {
            get {
                return ResourceManager.GetString("appMenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verknüpfung erfolgreich erstellt..
        /// </summary>
        internal static string appMenuItem4Msg0 {
            get {
                return ResourceManager.GetString("appMenuItem4Msg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verknüpfung konnte nicht erstellt werden..
        /// </summary>
        internal static string appMenuItem4Msg1 {
            get {
                return ResourceManager.GetString("appMenuItem4Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Taskleiste anheften.
        /// </summary>
        internal static string appMenuItem5 {
            get {
                return ResourceManager.GetString("appMenuItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbenennen.
        /// </summary>
        internal static string appMenuItem6 {
            get {
                return ResourceManager.GetString("appMenuItem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string appMenuItem7 {
            get {
                return ResourceManager.GetString("appMenuItem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie &apos;{0}&apos; wirklich löschen?.
        /// </summary>
        internal static string appMenuItem7Msg {
            get {
                return ResourceManager.GetString("appMenuItem7Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionen.
        /// </summary>
        internal static string appMenuItem8 {
            get {
                return ResourceManager.GetString("appMenuItem8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendung:.
        /// </summary>
        internal static string appsBoxLabel {
            get {
                return ResourceManager.GetString("appsBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} gefunden!.
        /// </summary>
        internal static string appsCount {
            get {
                return ResourceManager.GetString("appsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie sollen die Dateitypen zugewiesen werden?.
        /// </summary>
        internal static string AssociateAppWayQuestion {
            get {
                return ResourceManager.GetString("AssociateAppWayQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateitypen zuordnen.
        /// </summary>
        internal static string associateBtn {
            get {
                return ResourceManager.GetString("associateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben noch keine Dateitypen hinzugefügt..
        /// </summary>
        internal static string associateBtnMsg {
            get {
                return ResourceManager.GetString("associateBtnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Dateitypen sind bereits mit anderen Anwendungen verknüpft:
        ///
        ///{0}
        ///
        ///Möchten Sie dennoch fortfahren?.
        /// </summary>
        internal static string AssociateConflictMsg {
            get {
                return ResourceManager.GetString("AssociateConflictMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll dieser Dateityp immer mit dieser Anwendung geöffnet werden?.
        /// </summary>
        internal static string AssociateQuestionMsg0 {
            get {
                return ResourceManager.GetString("AssociateQuestionMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sollen die folgenden Dateitypen immer mit dieser Anwendung geöffnet werden?
        ///
        ///Dateitypen: {0}.
        /// </summary>
        internal static string AssociateQuestionMsg1 {
            get {
                return ResourceManager.GetString("AssociateQuestionMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Dateitypzuordnung.
        /// </summary>
        internal static string AssociateRestPointLabel {
            get {
                return ResourceManager.GetString("AssociateRestPointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte beachten Sie dass ein großes Bild den Start dieser Anwendung negativ beeinflussen kann..
        /// </summary>
        internal static string BgImageSizeInfoMsg {
            get {
                return ResourceManager.GetString("BgImageSizeInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anpassung:.
        /// </summary>
        internal static string bgLayoutLabel {
            get {
                return ResourceManager.GetString("bgLayoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine.
        /// </summary>
        internal static string bgLayoutOption0 {
            get {
                return ResourceManager.GetString("bgLayoutOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kachel.
        /// </summary>
        internal static string bgLayoutOption1 {
            get {
                return ResourceManager.GetString("bgLayoutOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentriert.
        /// </summary>
        internal static string bgLayoutOption2 {
            get {
                return ResourceManager.GetString("bgLayoutOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strecken.
        /// </summary>
        internal static string bgLayoutOption3 {
            get {
                return ResourceManager.GetString("bgLayoutOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausfüllen.
        /// </summary>
        internal static string bgLayoutOption4 {
            get {
                return ResourceManager.GetString("bgLayoutOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button-Farbe:.
        /// </summary>
        internal static string btnColorPanelLabel {
            get {
                return ResourceManager.GetString("btnColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button-Hover-Farbe:.
        /// </summary>
        internal static string btnHoverColorPanelLabel {
            get {
                return ResourceManager.GetString("btnHoverColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button-Text-Farbe:.
        /// </summary>
        internal static string btnTextColorPanelLabel {
            get {
                return ResourceManager.GetString("btnTextColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befehlszeile wurde aktualisiert..
        /// </summary>
        internal static string cmdLineUpdated {
            get {
                return ResourceManager.GetString("cmdLineUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control-Farbe:.
        /// </summary>
        internal static string controlColorPanelLabel {
            get {
                return ResourceManager.GetString("controlColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control-Text-Farbe:.
        /// </summary>
        internal static string controlTextColorPanelLabel {
            get {
                return ResourceManager.GetString("controlTextColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Ausrichtung:.
        /// </summary>
        internal static string defaultPosLabel {
            get {
                return ResourceManager.GetString("defaultPosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startmenü.
        /// </summary>
        internal static string defaultPosOption0 {
            get {
                return ResourceManager.GetString("defaultPosOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maus-Cursor.
        /// </summary>
        internal static string defaultPosOption1 {
            get {
                return ResourceManager.GetString("defaultPosOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Hintergrund.
        /// </summary>
        internal static string defBgCheck {
            get {
                return ResourceManager.GetString("defBgCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere hinzufügen.
        /// </summary>
        internal static string downloadBtn {
            get {
                return ResourceManager.GetString("downloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string exitBtn {
            get {
                return ResourceManager.GetString("exitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einblendeffekt:.
        /// </summary>
        internal static string fadeInComboLabel {
            get {
                return ResourceManager.GetString("fadeInComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einblenddauer:.
        /// </summary>
        internal static string fadeInNumLabel {
            get {
                return ResourceManager.GetString("fadeInNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateisystem wird abgerufen . . ..
        /// </summary>
        internal static string FileSystemAccessMsg {
            get {
                return ResourceManager.GetString("FileSystemAccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateitypen:.
        /// </summary>
        internal static string fileTypesLabel {
            get {
                return ResourceManager.GetString("fileTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        internal static string fileTypesMenuItem1 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügen.
        /// </summary>
        internal static string fileTypesMenuItem2 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Voreinstellung.
        /// </summary>
        internal static string fileTypesMenuItem3 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateitypen können einer Anwendung zugewiesen werden.
        ///
        ///Dateitypen die mit einem Punkt beginnen werden bei
        ///der Dateitypenzuordnung ausgeschlossen.
        ///
        ///Wird einer der eingetragenen Dateitypen mit dem
        ///Protable Apps Launcher geöffnet, wird diese App
        ///automatisch ausgewählt.
        ///Bei deaktivierter Bestätigungsabfrage wird die App,
        ///in folge dessen, ohne Nachfrage gestartet..
        /// </summary>
        internal static string fileTypesTip {
            get {
                return ResourceManager.GetString("fileTypesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrollbar ausblenden.
        /// </summary>
        internal static string hScrollBarCheck {
            get {
                return ResourceManager.GetString("hScrollBarCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptfarbe:.
        /// </summary>
        internal static string mainColorPanelLabel {
            get {
                return ResourceManager.GetString("mainColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Bestätigungsabfrage für diese App.
        /// </summary>
        internal static string noConfirmCheck {
            get {
                return ResourceManager.GetString("noConfirmCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn man diese Option aktiviert, werden
        ///definierte Dateitypen ohne Nachfrage mit
        ///der zugeordneten App gestartet..
        /// </summary>
        internal static string noConfirmCheckTip {
            get {
                return ResourceManager.GetString("noConfirmCheckTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Voreinstellung für diese Anwendung gefunden..
        /// </summary>
        internal static string NoDefaultTypesFoundMsg {
            get {
                return ResourceManager.GetString("NoDefaultTypesFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht gefunden....
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niemals nach Updates für diese App suchen.
        /// </summary>
        internal static string noUpdatesCheck {
            get {
                return ResourceManager.GetString("noUpdatesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Updates notwendig!.
        /// </summary>
        internal static string NoUpdatesFoundMsg {
            get {
                return ResourceManager.GetString("NoUpdatesFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deckkraft:.
        /// </summary>
        internal static string opacityNumLabel {
            get {
                return ResourceManager.GetString("opacityNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen mit:.
        /// </summary>
        internal static string OpenWithForm {
            get {
                return ResourceManager.GetString("OpenWithForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorgang wurde abgebrochen..
        /// </summary>
        internal static string OperationCanceledMsg {
            get {
                return ResourceManager.GetString("OperationCanceledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorgang wurde abgeschlossen..
        /// </summary>
        internal static string OperationCompletedMsg {
            get {
                return ResourceManager.GetString("OperationCompletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorgang ist fehlgeschlagen..
        /// </summary>
        internal static string OperationFailedMsg {
            get {
                return ResourceManager.GetString("OperationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Programm ist unvollständig. Möchten Sie es erneut herunterladen?.
        /// </summary>
        internal static string RequirementsErrorMsg {
            get {
                return ResourceManager.GetString("RequirementsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie diese Anwendung jetzt neu starten?.
        /// </summary>
        internal static string RestartQuestionMsg {
            get {
                return ResourceManager.GetString("RestartQuestionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateitypenzuordnung rückgängig machen..
        /// </summary>
        internal static string restoreFileTypesBtnTip {
            get {
                return ResourceManager.GetString("restoreFileTypesBtnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie die aktuellen Systemeinstellungen vor dem überschreiben sichern?
        ///
        ///Dadurch können Sie die folgenden Änderungen jederzeit wieder rückgängig machen..
        /// </summary>
        internal static string RestorePointMsg0 {
            get {
                return ResourceManager.GetString("RestorePointMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie zusätzlich einen Systemwiederherstellungspunkt erstellen?.
        /// </summary>
        internal static string RestorePointMsg1 {
            get {
                return ResourceManager.GetString("RestorePointMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie die vorherigen Systemeinstellungen wiederherstellen?.
        /// </summary>
        internal static string RestorePointMsg2 {
            get {
                return ResourceManager.GetString("RestorePointMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie dennoch zusätzlich die Systemwiederherstellung aufrufen?.
        /// </summary>
        internal static string RestorePointMsg3 {
            get {
                return ResourceManager.GetString("RestorePointMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die vorherigen Systemeinstellungen wurden erfolgreich wiederhergestellt..
        /// </summary>
        internal static string RestorePointMsg4 {
            get {
                return ResourceManager.GetString("RestorePointMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus der Shell entfernen.
        /// </summary>
        internal static string rmFromShellBtn {
            get {
                return ResourceManager.GetString("rmFromShellBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese App immer als Administrator ausführen.
        /// </summary>
        internal static string runAsAdminCheck {
            get {
                return ResourceManager.GetString("runAsAdminCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string saveBtn {
            get {
                return ResourceManager.GetString("saveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen erfolgreich gespeichert..
        /// </summary>
        internal static string SavedSettings {
            get {
                return ResourceManager.GetString("SavedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        internal static string searchBox {
            get {
                return ResourceManager.GetString("searchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hintergrund ändern.
        /// </summary>
        internal static string setBgBtn {
            get {
                return ResourceManager.GetString("setBgBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache (Language).
        /// </summary>
        internal static string setLangLabel {
            get {
                return ResourceManager.GetString("setLangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string settingsBtn {
            get {
                return ResourceManager.GetString("settingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Portable App weiterleiten.
        /// </summary>
        internal static string shellText {
            get {
                return ResourceManager.GetString("shellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Große Bilder anzeigen.
        /// </summary>
        internal static string showLargeImagesCheck {
            get {
                return ResourceManager.GetString("showLargeImagesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfade in Befehlszeilenargumenten sortieren.
        /// </summary>
        internal static string sortArgPathsCheck {
            get {
                return ResourceManager.GetString("sortArgPathsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derzeitige Befehlszeilenargumente..
        /// </summary>
        internal static string startArgsDefaultLabelTip {
            get {
                return ResourceManager.GetString("startArgsDefaultLabelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vor derzeitigen Befehlszeilenargumenten hinzufügen..
        /// </summary>
        internal static string startArgsFirstTip {
            get {
                return ResourceManager.GetString("startArgsFirstTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinter derzeitigen Befehlszeilenargumenten hinzufügen..
        /// </summary>
        internal static string startArgsLastTip {
            get {
                return ResourceManager.GetString("startArgsLastTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausführen.
        /// </summary>
        internal static string startBtn {
            get {
                return ResourceManager.GetString("startBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startmenü Integration:.
        /// </summary>
        internal static string startMenuIntegrationLabel {
            get {
                return ResourceManager.GetString("startMenuIntegrationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktiviert.
        /// </summary>
        internal static string startMenuIntegrationOption0 {
            get {
                return ResourceManager.GetString("startMenuIntegrationOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiviert.
        /// </summary>
        internal static string startMenuIntegrationOption1 {
            get {
                return ResourceManager.GetString("startMenuIntegrationOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App-Optionen.
        /// </summary>
        internal static string tabPage1 {
            get {
                return ResourceManager.GetString("tabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stil.
        /// </summary>
        internal static string tabPage2 {
            get {
                return ResourceManager.GetString("tabPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstiges.
        /// </summary>
        internal static string tabPage3 {
            get {
                return ResourceManager.GetString("tabPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach Updates suchen.
        /// </summary>
        internal static string updateBtn {
            get {
                return ResourceManager.GetString("updateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update-Channel.
        /// </summary>
        internal static string updateChannelLabel {
            get {
                return ResourceManager.GetString("updateChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string updateChannelOption0 {
            get {
                return ResourceManager.GetString("updateChannelOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string updateChannelOption1 {
            get {
                return ResourceManager.GetString("updateChannelOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update-Suche:.
        /// </summary>
        internal static string updateCheckLabel {
            get {
                return ResourceManager.GetString("updateCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niemals.
        /// </summary>
        internal static string updateCheckOption0 {
            get {
                return ResourceManager.GetString("updateCheckOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stündlich (Komplett).
        /// </summary>
        internal static string updateCheckOption1 {
            get {
                return ResourceManager.GetString("updateCheckOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stündlich (Nur Apps).
        /// </summary>
        internal static string updateCheckOption2 {
            get {
                return ResourceManager.GetString("updateCheckOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stündlich (Nur Port-Able).
        /// </summary>
        internal static string updateCheckOption3 {
            get {
                return ResourceManager.GetString("updateCheckOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Täglich (Komplett).
        /// </summary>
        internal static string updateCheckOption4 {
            get {
                return ResourceManager.GetString("updateCheckOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Täglich (Nur Apps).
        /// </summary>
        internal static string updateCheckOption5 {
            get {
                return ResourceManager.GetString("updateCheckOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Täglich (Nur Port-Able).
        /// </summary>
        internal static string updateCheckOption6 {
            get {
                return ResourceManager.GetString("updateCheckOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monatlich (Komplett).
        /// </summary>
        internal static string updateCheckOption7 {
            get {
                return ResourceManager.GetString("updateCheckOption7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monatlich (Nur Apps).
        /// </summary>
        internal static string updateCheckOption8 {
            get {
                return ResourceManager.GetString("updateCheckOption8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monatlich (Nur Port-Able).
        /// </summary>
        internal static string updateCheckOption9 {
            get {
                return ResourceManager.GetString("updateCheckOption9", resourceCulture);
            }
        }
    }
}
