//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsLauncher.LangResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsLauncher.LangResources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Port-Able.
        /// </summary>
        internal static string AboutForm {
            get {
                return ResourceManager.GetString("AboutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port-Able is developed and designed by {0}, founded
        ///and managed by Roy Schroedel.
        ///
        ///Would you like to support me? {1} or {2}!
        ///Suggestions are also very welcome!.
        /// </summary>
        internal static string aboutInfoLabel {
            get {
                return ResourceManager.GetString("aboutInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate by Paypal.
        /// </summary>
        internal static string aboutInfoLabelLinkLabel1 {
            get {
                return ResourceManager.GetString("aboutInfoLabelLinkLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an Issue.
        /// </summary>
        internal static string aboutInfoLabelLinkLabel2 {
            get {
                return ResourceManager.GetString("aboutInfoLabelLinkLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Arguments:.
        /// </summary>
        internal static string addArgsLabel {
            get {
                return ResourceManager.GetString("addArgsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to current command line arguments..
        /// </summary>
        internal static string addArgsLabelTip {
            get {
                return ResourceManager.GetString("addArgsLabelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more apps..
        /// </summary>
        internal static string addBtnTip {
            get {
                return ResourceManager.GetString("addBtnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate to Shell.
        /// </summary>
        internal static string addToShellBtn {
            get {
                return ResourceManager.GetString("addToShellBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Directories:.
        /// </summary>
        internal static string appDirsLabel {
            get {
                return ResourceManager.GetString("appDirsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more directories that contain portable apps:
        ///
        ///- Set full directories
        ///- One directory per line
        ///- Environment variables are accepted.
        /// </summary>
        internal static string appDirsTip {
            get {
                return ResourceManager.GetString("appDirsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string appMenuItem1 {
            get {
                return ResourceManager.GetString("appMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator.
        /// </summary>
        internal static string appMenuItem2 {
            get {
                return ResourceManager.GetString("appMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open app location.
        /// </summary>
        internal static string appMenuItem3 {
            get {
                return ResourceManager.GetString("appMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create desktop shortcut.
        /// </summary>
        internal static string appMenuItem4 {
            get {
                return ResourceManager.GetString("appMenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut successfully created..
        /// </summary>
        internal static string appMenuItem4Msg0 {
            get {
                return ResourceManager.GetString("appMenuItem4Msg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut could not be created..
        /// </summary>
        internal static string appMenuItem4Msg1 {
            get {
                return ResourceManager.GetString("appMenuItem4Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to taskbar.
        /// </summary>
        internal static string appMenuItem5 {
            get {
                return ResourceManager.GetString("appMenuItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string appMenuItem6 {
            get {
                return ResourceManager.GetString("appMenuItem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string appMenuItem7 {
            get {
                return ResourceManager.GetString("appMenuItem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string appMenuItem7Msg {
            get {
                return ResourceManager.GetString("appMenuItem7Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string appMenuItem8 {
            get {
                return ResourceManager.GetString("appMenuItem8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application:.
        /// </summary>
        internal static string appsBoxLabel {
            get {
                return ResourceManager.GetString("appsBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} found!.
        /// </summary>
        internal static string appsCount {
            get {
                return ResourceManager.GetString("appsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are the file types to be assigned?.
        /// </summary>
        internal static string AssociateAppWayQuestion {
            get {
                return ResourceManager.GetString("AssociateAppWayQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate File Types.
        /// </summary>
        internal static string associateBtn {
            get {
                return ResourceManager.GetString("associateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add some file types before you use this option..
        /// </summary>
        internal static string associateBtnMsg {
            get {
                return ResourceManager.GetString("associateBtnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file types are already defined for a different app:
        ///
        ///{0}
        ///
        ///Do you want to continue?.
        /// </summary>
        internal static string AssociateConflictMsg {
            get {
                return ResourceManager.GetString("AssociateConflictMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you always want to open this kind of file with this application?.
        /// </summary>
        internal static string AssociateQuestionMsg0 {
            get {
                return ResourceManager.GetString("AssociateQuestionMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you always want to open the following file types with this application?
        ///
        ///Types: {0}.
        /// </summary>
        internal static string AssociateQuestionMsg1 {
            get {
                return ResourceManager.GetString("AssociateQuestionMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - File Type Assotiation.
        /// </summary>
        internal static string AssociateRestPointLabel {
            get {
                return ResourceManager.GetString("AssociateRestPointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that a large picture may negatively affect the start of this application..
        /// </summary>
        internal static string BgImageSizeInfoMsg {
            get {
                return ResourceManager.GetString("BgImageSizeInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout:.
        /// </summary>
        internal static string bgLayoutLabel {
            get {
                return ResourceManager.GetString("bgLayoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string bgLayoutOption0 {
            get {
                return ResourceManager.GetString("bgLayoutOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        internal static string bgLayoutOption1 {
            get {
                return ResourceManager.GetString("bgLayoutOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string bgLayoutOption2 {
            get {
                return ResourceManager.GetString("bgLayoutOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        internal static string bgLayoutOption3 {
            get {
                return ResourceManager.GetString("bgLayoutOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string bgLayoutOption4 {
            get {
                return ResourceManager.GetString("bgLayoutOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Color:.
        /// </summary>
        internal static string btnColorPanelLabel {
            get {
                return ResourceManager.GetString("btnColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Hover Color:.
        /// </summary>
        internal static string btnHoverColorPanelLabel {
            get {
                return ResourceManager.GetString("btnHoverColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Text Color:.
        /// </summary>
        internal static string btnTextColorPanelLabel {
            get {
                return ResourceManager.GetString("btnTextColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command-Line arguments has been updated..
        /// </summary>
        internal static string cmdLineUpdated {
            get {
                return ResourceManager.GetString("cmdLineUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Color:.
        /// </summary>
        internal static string controlColorPanelLabel {
            get {
                return ResourceManager.GetString("controlColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Text Color:.
        /// </summary>
        internal static string controlTextColorPanelLabel {
            get {
                return ResourceManager.GetString("controlTextColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Location.
        /// </summary>
        internal static string defaultPosLabel {
            get {
                return ResourceManager.GetString("defaultPosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align to Start Menu.
        /// </summary>
        internal static string defaultPosOption0 {
            get {
                return ResourceManager.GetString("defaultPosOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align to Mouse Cursor.
        /// </summary>
        internal static string defaultPosOption1 {
            get {
                return ResourceManager.GetString("defaultPosOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Background.
        /// </summary>
        internal static string defBgCheck {
            get {
                return ResourceManager.GetString("defBgCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More.
        /// </summary>
        internal static string downloadBtn {
            get {
                return ResourceManager.GetString("downloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exitBtn {
            get {
                return ResourceManager.GetString("exitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade In Effect:.
        /// </summary>
        internal static string fadeInComboLabel {
            get {
                return ResourceManager.GetString("fadeInComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade In Duration:.
        /// </summary>
        internal static string fadeInNumLabel {
            get {
                return ResourceManager.GetString("fadeInNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system is being accessed . . ..
        /// </summary>
        internal static string FileSystemAccessMsg {
            get {
                return ResourceManager.GetString("FileSystemAccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Types:.
        /// </summary>
        internal static string fileTypesLabel {
            get {
                return ResourceManager.GetString("fileTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string fileTypesMenuItem1 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string fileTypesMenuItem2 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Default.
        /// </summary>
        internal static string fileTypesMenuItem3 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File types can be associated with an app. When you send
        ///a file to this application, the first associated app is
        ///selected by default..
        /// </summary>
        internal static string fileTypesTip {
            get {
                return ResourceManager.GetString("fileTypesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Horizontal Scrollbar.
        /// </summary>
        internal static string hScrollBarCheck {
            get {
                return ResourceManager.GetString("hScrollBarCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Color:.
        /// </summary>
        internal static string mainColorPanelLabel {
            get {
                return ResourceManager.GetString("mainColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable confirmation for this app.
        /// </summary>
        internal static string noConfirmCheck {
            get {
                return ResourceManager.GetString("noConfirmCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the file type associated app
        ///without confirmation..
        /// </summary>
        internal static string noConfirmCheckTip {
            get {
                return ResourceManager.GetString("noConfirmCheckTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default types found for this application..
        /// </summary>
        internal static string NoDefaultTypesFoundMsg {
            get {
                return ResourceManager.GetString("NoDefaultTypesFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found....
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never search updates for this app.
        /// </summary>
        internal static string noUpdatesCheck {
            get {
                return ResourceManager.GetString("noUpdatesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates necessary!.
        /// </summary>
        internal static string NoUpdatesFoundMsg {
            get {
                return ResourceManager.GetString("NoUpdatesFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity:.
        /// </summary>
        internal static string opacityNumLabel {
            get {
                return ResourceManager.GetString("opacityNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with:.
        /// </summary>
        internal static string OpenWithForm {
            get {
                return ResourceManager.GetString("OpenWithForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled..
        /// </summary>
        internal static string OperationCanceledMsg {
            get {
                return ResourceManager.GetString("OperationCanceledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed..
        /// </summary>
        internal static string OperationCompletedMsg {
            get {
                return ResourceManager.GetString("OperationCompletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        internal static string OperationFailedMsg {
            get {
                return ResourceManager.GetString("OperationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is incomplete. Would you like to download it again?.
        /// </summary>
        internal static string RequirementsErrorMsg {
            get {
                return ResourceManager.GetString("RequirementsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to restart this application now?.
        /// </summary>
        internal static string RestartQuestionMsg {
            get {
                return ResourceManager.GetString("RestartQuestionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore file type association..
        /// </summary>
        internal static string restoreFileTypesBtnTip {
            get {
                return ResourceManager.GetString("restoreFileTypesBtnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current system settings before overwriting?
        ///
        ///This will allow you to go back in time and undo the following changes..
        /// </summary>
        internal static string RestorePointMsg0 {
            get {
                return ResourceManager.GetString("RestorePointMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you also want to create a system restore point?.
        /// </summary>
        internal static string RestorePointMsg1 {
            get {
                return ResourceManager.GetString("RestorePointMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restore the previous system settings?.
        /// </summary>
        internal static string RestorePointMsg2 {
            get {
                return ResourceManager.GetString("RestorePointMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you also want to restore a previously created system restore point?.
        /// </summary>
        internal static string RestorePointMsg3 {
            get {
                return ResourceManager.GetString("RestorePointMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous system settings were successfully restored..
        /// </summary>
        internal static string RestorePointMsg4 {
            get {
                return ResourceManager.GetString("RestorePointMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Shell.
        /// </summary>
        internal static string rmFromShellBtn {
            get {
                return ResourceManager.GetString("rmFromShellBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this app always with administrator privileges.
        /// </summary>
        internal static string runAsAdminCheck {
            get {
                return ResourceManager.GetString("runAsAdminCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string saveBtn {
            get {
                return ResourceManager.GetString("saveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings successfully saved..
        /// </summary>
        internal static string SavedSettings {
            get {
                return ResourceManager.GetString("SavedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string searchBox {
            get {
                return ResourceManager.GetString("searchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Background.
        /// </summary>
        internal static string setBgBtn {
            get {
                return ResourceManager.GetString("setBgBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string setLangLabel {
            get {
                return ResourceManager.GetString("setLangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsBtn {
            get {
                return ResourceManager.GetString("settingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Portable App.
        /// </summary>
        internal static string shellText {
            get {
                return ResourceManager.GetString("shellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Large Images.
        /// </summary>
        internal static string showLargeImagesCheck {
            get {
                return ResourceManager.GetString("showLargeImagesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort paths in command line arguments.
        /// </summary>
        internal static string sortArgPathsCheck {
            get {
                return ResourceManager.GetString("sortArgPathsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current command-line arguments..
        /// </summary>
        internal static string startArgsDefaultLabelTip {
            get {
                return ResourceManager.GetString("startArgsDefaultLabelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add before the current command line arguments..
        /// </summary>
        internal static string startArgsFirstTip {
            get {
                return ResourceManager.GetString("startArgsFirstTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add after the current command line arguments..
        /// </summary>
        internal static string startArgsLastTip {
            get {
                return ResourceManager.GetString("startArgsLastTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string startBtn {
            get {
                return ResourceManager.GetString("startBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Menu integration:.
        /// </summary>
        internal static string startMenuIntegrationLabel {
            get {
                return ResourceManager.GetString("startMenuIntegrationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string startMenuIntegrationOption0 {
            get {
                return ResourceManager.GetString("startMenuIntegrationOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string startMenuIntegrationOption1 {
            get {
                return ResourceManager.GetString("startMenuIntegrationOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Options.
        /// </summary>
        internal static string tabPage1 {
            get {
                return ResourceManager.GetString("tabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string tabPage2 {
            get {
                return ResourceManager.GetString("tabPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string tabPage3 {
            get {
                return ResourceManager.GetString("tabPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string updateBtn {
            get {
                return ResourceManager.GetString("updateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel.
        /// </summary>
        internal static string updateChannelLabel {
            get {
                return ResourceManager.GetString("updateChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string updateChannelOption0 {
            get {
                return ResourceManager.GetString("updateChannelOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string updateChannelOption1 {
            get {
                return ResourceManager.GetString("updateChannelOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Updates:.
        /// </summary>
        internal static string updateCheckLabel {
            get {
                return ResourceManager.GetString("updateCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string updateCheckOption0 {
            get {
                return ResourceManager.GetString("updateCheckOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly (full).
        /// </summary>
        internal static string updateCheckOption1 {
            get {
                return ResourceManager.GetString("updateCheckOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly (only apps).
        /// </summary>
        internal static string updateCheckOption2 {
            get {
                return ResourceManager.GetString("updateCheckOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly (only Port-Able).
        /// </summary>
        internal static string updateCheckOption3 {
            get {
                return ResourceManager.GetString("updateCheckOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily (full).
        /// </summary>
        internal static string updateCheckOption4 {
            get {
                return ResourceManager.GetString("updateCheckOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily (only apps).
        /// </summary>
        internal static string updateCheckOption5 {
            get {
                return ResourceManager.GetString("updateCheckOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily (only Port-Able).
        /// </summary>
        internal static string updateCheckOption6 {
            get {
                return ResourceManager.GetString("updateCheckOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly (full).
        /// </summary>
        internal static string updateCheckOption7 {
            get {
                return ResourceManager.GetString("updateCheckOption7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly (only apps).
        /// </summary>
        internal static string updateCheckOption8 {
            get {
                return ResourceManager.GetString("updateCheckOption8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly (only Port-Able).
        /// </summary>
        internal static string updateCheckOption9 {
            get {
                return ResourceManager.GetString("updateCheckOption9", resourceCulture);
            }
        }
    }
}
