//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsDownloader.LangResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsDownloader.LangResources.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App erfolgreich heruntergeladen!.
        /// </summary>
        internal static string AppDownloadedMsg {
            get {
                return ResourceManager.GetString("AppDownloadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leider gab es einige Probleme beim herunterladen der folgenden App:
        ///
        ///{0}
        ///
        ///Dies könnte mit einem unvollständigen Download, oder einem anderen Netzwerkproblem, in Verbindung stehen..
        /// </summary>
        internal static string AppDownloadErrorMsg {
            get {
                return ResourceManager.GetString("AppDownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte beachten Sie das eine IPv4-Verbindung zwingend erforderlich ist um Daten von &apos;{0}&apos; herunterzuladen..
        /// </summary>
        internal static string AppInternetProtocolWarningMsg {
            get {
                return ResourceManager.GetString("AppInternetProtocolWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendungsliste.
        /// </summary>
        internal static string appListGroupBox {
            get {
                return ResourceManager.GetString("appListGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswählen.
        /// </summary>
        internal static string appMenuItem1 {
            get {
                return ResourceManager.GetString("appMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abwählen.
        /// </summary>
        internal static string appMenuItem1u {
            get {
                return ResourceManager.GetString("appMenuItem1u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles auswählen.
        /// </summary>
        internal static string appMenuItem2 {
            get {
                return ResourceManager.GetString("appMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles abwählen.
        /// </summary>
        internal static string appMenuItem2u {
            get {
                return ResourceManager.GetString("appMenuItem2u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Browser öffnen.
        /// </summary>
        internal static string appMenuItem3 {
            get {
                return ResourceManager.GetString("appMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige erweiterte Informationen.
        /// </summary>
        internal static string appMenuItem4 {
            get {
                return ResourceManager.GetString("appMenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps erfolgreich heruntergeladen!.
        /// </summary>
        internal static string AppsDownloadedMsg {
            get {
                return ResourceManager.GetString("AppsDownloadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leider gab es einige Probleme beim herunterladen der folgenden Apps:
        ///
        ///{0}
        ///
        ///Dies könnte mit einem unvollständigen Download, oder einem anderen Netzwerkproblem, in Verbindung stehen..
        /// </summary>
        internal static string AppsDownloadErrorMsg {
            get {
                return ResourceManager.GetString("AppsDownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendung:.
        /// </summary>
        internal static string appStatusLabel {
            get {
                return ResourceManager.GetString("appStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps erfolgreich aktualisiert!.
        /// </summary>
        internal static string AppsUpdatedMsg {
            get {
                return ResourceManager.GetString("AppsUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Aktualisierung verfügbar. Möchten Sie fortfahren?.
        /// </summary>
        internal static string AppUpdateAvailableMsg {
            get {
                return ResourceManager.GetString("AppUpdateAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App erfolgreich aktualisiert!.
        /// </summary>
        internal static string AppUpdatedMsg {
            get {
                return ResourceManager.GetString("AppUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Aktualisierungen verfügbar. Möchten Sie fortfahren?.
        /// </summary>
        internal static string AppUpdatesAvailableMsg {
            get {
                return ResourceManager.GetString("AppUpdatesAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher?.
        /// </summary>
        internal static string AreYouSureMsg {
            get {
                return ResourceManager.GetString("AreYouSureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrikaans,Albanian,Arabic,Armenian,Basque,Belarusian,Bulgarian,Catalan,Croatian,Czech,Danish,Dutch,EnglishGB,Estonian,Farsi,Filipino,Finnish,French,Galician,German,Greek,Hebrew,Hungarian,Indonesian,Japanese,Irish,Italian,Korean,Latvian,Lithuanian,Luxembourgish,Macedonian,Malay,Norwegian,Polish,Portuguese,PortugueseBR,Romanian,Russian,Serbian,SerbianLatin,SimpChinese,Slovak,Slovenian,Spanish,SpanishInternational,Sundanese,Swedish,Thai,TradChinese,Turkish,Ukrainian,Vietnamese.
        /// </summary>
        internal static string availableLangs {
            get {
                return ResourceManager.GetString("availableLangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendung.
        /// </summary>
        internal static string columnHeader1 {
            get {
                return ResourceManager.GetString("columnHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string columnHeader2 {
            get {
                return ResourceManager.GetString("columnHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string columnHeader3 {
            get {
                return ResourceManager.GetString("columnHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloadgröße.
        /// </summary>
        internal static string columnHeader4 {
            get {
                return ResourceManager.GetString("columnHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installierte Größe.
        /// </summary>
        internal static string columnHeader5 {
            get {
                return ResourceManager.GetString("columnHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle.
        /// </summary>
        internal static string columnHeader6 {
            get {
                return ResourceManager.GetString("columnHeader6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank wird abgerufen . . ..
        /// </summary>
        internal static string DatabaseAccessMsg {
            get {
                return ResourceManager.GetString("DatabaseAccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heruntergeladen:.
        /// </summary>
        internal static string downloadReceivedLabel {
            get {
                return ResourceManager.GetString("downloadReceivedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den Vorgang  wiederholen?.
        /// </summary>
        internal static string DownloadRetryMsg {
            get {
                return ResourceManager.GetString("DownloadRetryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschwindigkeit:.
        /// </summary>
        internal static string downloadSpeedLabel {
            get {
                return ResourceManager.GetString("downloadSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der folgende Prozess wird beendet:
        ///
        ///{0}
        ///
        ///Bitte stellen Sie sicher dass Ihre Einstellungen gespeichert sind, bevor Sie diese Meldung bestätigen!.
        /// </summary>
        internal static string FileLockMsg {
            get {
                return ResourceManager.GetString("FileLockMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Prozesse werden beendet:
        ///
        ///{0}
        ///
        ///Bitte stellen Sie sicher dass Ihre Einstellungen gespeichert sind, bevor Sie diese Meldung bestätigen!.
        /// </summary>
        internal static string FileLocksMsg {
            get {
                return ResourceManager.GetString("FileLocksMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei:.
        /// </summary>
        internal static string fileStatusLabel {
            get {
                return ResourceManager.GetString("fileStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppenfarben.
        /// </summary>
        internal static string groupColorsGroupBox {
            get {
                return ResourceManager.GetString("groupColorsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installierte hervorheben.
        /// </summary>
        internal static string highlightInstalledCheck {
            get {
                return ResourceManager.GetString("highlightInstalledCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisiere, bitte warten . . ..
        /// </summary>
        internal static string InitializingMsg {
            get {
                return ResourceManager.GetString("InitializingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisiere, bitte warten....
        /// </summary>
        internal static string InitStatusText {
            get {
                return ResourceManager.GetString("InitStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Installation wurde übersprungen!.
        /// </summary>
        internal static string InstallSkippedMsg {
            get {
                return ResourceManager.GetString("InstallSkippedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Internetverbindung hergestellt werden..
        /// </summary>
        internal static string InternetIsNotAvailableMsg {
            get {
                return ResourceManager.GetString("InternetIsNotAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Ihrem System konnte keine IPv4-Verbindung aufgebaut werden. Das kann zu unerwünschten Problemen führen..
        /// </summary>
        internal static string InternetProtocolWarningMsg {
            get {
                return ResourceManager.GetString("InternetProtocolWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachauswahl:.
        /// </summary>
        internal static string LangSelectionForm {
            get {
                return ResourceManager.GetString("LangSelectionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S U C H E.
        /// </summary>
        internal static string listViewGroup0 {
            get {
                return ResourceManager.GetString("listViewGroup0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrierefreiheit.
        /// </summary>
        internal static string listViewGroup1 {
            get {
                return ResourceManager.GetString("listViewGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiele.
        /// </summary>
        internal static string listViewGroup10 {
            get {
                return ResourceManager.GetString("listViewGroup10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Erweitert.
        /// </summary>
        internal static string listViewGroup11 {
            get {
                return ResourceManager.GetString("listViewGroup11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Benutzerdefiniert.
        /// </summary>
        internal static string listViewGroup12 {
            get {
                return ResourceManager.GetString("listViewGroup12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildung.
        /// </summary>
        internal static string listViewGroup2 {
            get {
                return ResourceManager.GetString("listViewGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entwicklung.
        /// </summary>
        internal static string listViewGroup3 {
            get {
                return ResourceManager.GetString("listViewGroup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büro.
        /// </summary>
        internal static string listViewGroup4 {
            get {
                return ResourceManager.GetString("listViewGroup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string listViewGroup5 {
            get {
                return ResourceManager.GetString("listViewGroup5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos und Bilder.
        /// </summary>
        internal static string listViewGroup6 {
            get {
                return ResourceManager.GetString("listViewGroup6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio und Video.
        /// </summary>
        internal static string listViewGroup7 {
            get {
                return ResourceManager.GetString("listViewGroup7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherheit.
        /// </summary>
        internal static string listViewGroup8 {
            get {
                return ResourceManager.GetString("listViewGroup8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschiedenes.
        /// </summary>
        internal static string listViewGroup9 {
            get {
                return ResourceManager.GetString("listViewGroup9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leider konnte keine Verbindung zum Server aufgebaut werden.
        ///Bitte versuchen Sie es später noch einmal..
        /// </summary>
        internal static string NoServerAvailableMsg {
            get {
                return ResourceManager.GetString("NoServerAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf dem Speichergerät ({0}:\) ist nicht genügend freier Speicherplatz vorhanden.
        ///
        ///Es muss mindestens {1} mehr Speicherplatz freigeben werden..
        /// </summary>
        internal static string NotEnoughSpaceMsg {
            get {
                return ResourceManager.GetString("NotEnoughSpaceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorgang wurde abgebrochen..
        /// </summary>
        internal static string OperationCanceledMsg {
            get {
                return ResourceManager.GetString("OperationCanceledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorgang wurde abgeschlossen..
        /// </summary>
        internal static string OperationCompletedMsg {
            get {
                return ResourceManager.GetString("OperationCompletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorgang ist fehlgeschlagen..
        /// </summary>
        internal static string OperationFailedMsg {
            get {
                return ResourceManager.GetString("OperationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellung für diese Anwendung merken.
        /// </summary>
        internal static string rememberLangCheck {
            get {
                return ResourceManager.GetString("rememberLangCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Programm ist unvollständig. Möchten Sie es erneut herunterladen?.
        /// </summary>
        internal static string RequirementsErrorMsg {
            get {
                return ResourceManager.GetString("RequirementsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string SettingsForm {
            get {
                return ResourceManager.GetString("SettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppenfarben anzeigen.
        /// </summary>
        internal static string showColorsCheck {
            get {
                return ResourceManager.GetString("showColorsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen anzeigen.
        /// </summary>
        internal static string showGroupsCheck {
            get {
                return ResourceManager.GetString("showGroupsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Große Bilder anzeigen.
        /// </summary>
        internal static string showLargeImagesCheck {
            get {
                return ResourceManager.GetString("showLargeImagesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string startBtn {
            get {
                return ResourceManager.GetString("startBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verstrichene Zeit:.
        /// </summary>
        internal static string timeStatusLabel {
            get {
                return ResourceManager.GetString("timeStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei: {0}/{1}.
        /// </summary>
        internal static string titleStatus {
            get {
                return ResourceManager.GetString("titleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das benutzerdefinierte Übertragungsverzeichnis kann sich nicht auf demselben Speichergerät wie die Suite befinden..
        /// </summary>
        internal static string TransferDirDriveMsg {
            get {
                return ResourceManager.GetString("TransferDirDriveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übertragungsverzeichnis.
        /// </summary>
        internal static string transferGroupBox {
            get {
                return ResourceManager.GetString("transferGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle:.
        /// </summary>
        internal static string urlStatusLabel {
            get {
                return ResourceManager.GetString("urlStatusLabel", resourceCulture);
            }
        }
    }
}
