//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsDownloader.LangResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsDownloader.LangResources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App successfully downloaded!.
        /// </summary>
        internal static string AppDownloadedMsg {
            get {
                return ResourceManager.GetString("AppDownloadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems installing the following app:
        ///
        ///{0}
        ///
        ///This could be due an incomplete download or other network issue..
        /// </summary>
        internal static string AppDownloadErrorMsg {
            get {
                return ResourceManager.GetString("AppDownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that an IPv4 connection is required to download resources from &apos;{0}&apos;..
        /// </summary>
        internal static string AppInternetProtocolWarningMsg {
            get {
                return ResourceManager.GetString("AppInternetProtocolWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application List.
        /// </summary>
        internal static string appListGroupBox {
            get {
                return ResourceManager.GetString("appListGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string appMenuItem1 {
            get {
                return ResourceManager.GetString("appMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unheck.
        /// </summary>
        internal static string appMenuItem1u {
            get {
                return ResourceManager.GetString("appMenuItem1u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        internal static string appMenuItem2 {
            get {
                return ResourceManager.GetString("appMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck All.
        /// </summary>
        internal static string appMenuItem2u {
            get {
                return ResourceManager.GetString("appMenuItem2u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        internal static string appMenuItem3 {
            get {
                return ResourceManager.GetString("appMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show advanced information.
        /// </summary>
        internal static string appMenuItem4 {
            get {
                return ResourceManager.GetString("appMenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps successfully downloaded!.
        /// </summary>
        internal static string AppsDownloadedMsg {
            get {
                return ResourceManager.GetString("AppsDownloadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems installing the following apps:
        ///
        ///{0}
        ///
        ///This could be due an incomplete download or other network issue..
        /// </summary>
        internal static string AppsDownloadErrorMsg {
            get {
                return ResourceManager.GetString("AppsDownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application:.
        /// </summary>
        internal static string appStatusLabel {
            get {
                return ResourceManager.GetString("appStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps successfully updated!.
        /// </summary>
        internal static string AppsUpdatedMsg {
            get {
                return ResourceManager.GetString("AppsUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} update is available. Would you like to update now?.
        /// </summary>
        internal static string AppUpdateAvailableMsg {
            get {
                return ResourceManager.GetString("AppUpdateAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App successfully updated!.
        /// </summary>
        internal static string AppUpdatedMsg {
            get {
                return ResourceManager.GetString("AppUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updates are available. Would you like to update now?.
        /// </summary>
        internal static string AppUpdatesAvailableMsg {
            get {
                return ResourceManager.GetString("AppUpdatesAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSureMsg {
            get {
                return ResourceManager.GetString("AreYouSureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the checksum of the following file:
        ///
        ///{0}
        ///
        ///In some cases, it&apos;s just a little synchronization problem in the online database. However, this could also be due to an incomplete download or other issue..
        /// </summary>
        internal static string ChecksumErrorMsg {
            get {
                return ResourceManager.GetString("ChecksumErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string columnHeader1 {
            get {
                return ResourceManager.GetString("columnHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string columnHeader2 {
            get {
                return ResourceManager.GetString("columnHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string columnHeader3 {
            get {
                return ResourceManager.GetString("columnHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Size.
        /// </summary>
        internal static string columnHeader4 {
            get {
                return ResourceManager.GetString("columnHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Size.
        /// </summary>
        internal static string columnHeader5 {
            get {
                return ResourceManager.GetString("columnHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string columnHeader6 {
            get {
                return ResourceManager.GetString("columnHeader6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is being accessed . . ..
        /// </summary>
        internal static string DatabaseAccessMsg {
            get {
                return ResourceManager.GetString("DatabaseAccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded:.
        /// </summary>
        internal static string downloadReceivedLabel {
            get {
                return ResourceManager.GetString("downloadReceivedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to retry?.
        /// </summary>
        internal static string DownloadRetryMsg {
            get {
                return ResourceManager.GetString("DownloadRetryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        internal static string downloadSpeedLabel {
            get {
                return ResourceManager.GetString("downloadSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following process must be closed:
        ///
        ///{0}
        ///
        ///Please make sure your settings are saved before confirming this message!.
        /// </summary>
        internal static string FileLockMsg {
            get {
                return ResourceManager.GetString("FileLockMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following processes must be closed:
        ///
        ///{0}
        ///
        ///Please make sure your settings are saved before confirming this message!.
        /// </summary>
        internal static string FileLocksMsg {
            get {
                return ResourceManager.GetString("FileLocksMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        internal static string fileStatusLabel {
            get {
                return ResourceManager.GetString("fileStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Colors.
        /// </summary>
        internal static string groupColorsGroupBox {
            get {
                return ResourceManager.GetString("groupColorsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Installed.
        /// </summary>
        internal static string highlightInstalledCheck {
            get {
                return ResourceManager.GetString("highlightInstalledCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Not available . . . ].
        /// </summary>
        internal static string HostNotAvailable {
            get {
                return ResourceManager.GetString("HostNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing, please wait . . ..
        /// </summary>
        internal static string InitializingMsg {
            get {
                return ResourceManager.GetString("InitializingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing, please wait....
        /// </summary>
        internal static string InitStatusText {
            get {
                return ResourceManager.GetString("InitStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} installation skipped!.
        /// </summary>
        internal static string InstallSkippedMsg {
            get {
                return ResourceManager.GetString("InstallSkippedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is no internet connection available..
        /// </summary>
        internal static string InternetIsNotAvailableMsg {
            get {
                return ResourceManager.GetString("InternetIsNotAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IPv4 connection could not be established on your system. This can lead to unwanted problems..
        /// </summary>
        internal static string InternetProtocolWarningMsg {
            get {
                return ResourceManager.GetString("InternetProtocolWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selection:.
        /// </summary>
        internal static string LangSelectionForm {
            get {
                return ResourceManager.GetString("LangSelectionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S E A R C H.
        /// </summary>
        internal static string listViewGroup0 {
            get {
                return ResourceManager.GetString("listViewGroup0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string listViewGroup1 {
            get {
                return ResourceManager.GetString("listViewGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string listViewGroup10 {
            get {
                return ResourceManager.GetString("listViewGroup10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Advanced.
        /// </summary>
        internal static string listViewGroup11 {
            get {
                return ResourceManager.GetString("listViewGroup11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Custom.
        /// </summary>
        internal static string listViewGroup12 {
            get {
                return ResourceManager.GetString("listViewGroup12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string listViewGroup2 {
            get {
                return ResourceManager.GetString("listViewGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string listViewGroup3 {
            get {
                return ResourceManager.GetString("listViewGroup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string listViewGroup4 {
            get {
                return ResourceManager.GetString("listViewGroup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string listViewGroup5 {
            get {
                return ResourceManager.GetString("listViewGroup5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics and Pictures.
        /// </summary>
        internal static string listViewGroup6 {
            get {
                return ResourceManager.GetString("listViewGroup6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music and Video.
        /// </summary>
        internal static string listViewGroup7 {
            get {
                return ResourceManager.GetString("listViewGroup7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string listViewGroup8 {
            get {
                return ResourceManager.GetString("listViewGroup8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string listViewGroup9 {
            get {
                return ResourceManager.GetString("listViewGroup9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there are currently no download servers available.
        ///Please try again later..
        /// </summary>
        internal static string NoServerAvailableMsg {
            get {
                return ResourceManager.GetString("NoServerAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough free space on the storage device ({0}:\).
        ///
        ///You must free up at least {1} more space..
        /// </summary>
        internal static string NotEnoughSpaceMsg {
            get {
                return ResourceManager.GetString("NotEnoughSpaceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled..
        /// </summary>
        internal static string OperationCanceledMsg {
            get {
                return ResourceManager.GetString("OperationCanceledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed..
        /// </summary>
        internal static string OperationCompletedMsg {
            get {
                return ResourceManager.GetString("OperationCompletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        internal static string OperationFailedMsg {
            get {
                return ResourceManager.GetString("OperationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not ask again for this application.
        /// </summary>
        internal static string rememberLangCheck {
            get {
                return ResourceManager.GetString("rememberLangCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is incomplete. Would you like to download it again?.
        /// </summary>
        internal static string RequirementsErrorMsg {
            get {
                return ResourceManager.GetString("RequirementsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsForm {
            get {
                return ResourceManager.GetString("SettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Group Colors.
        /// </summary>
        internal static string showColorsCheck {
            get {
                return ResourceManager.GetString("showColorsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Groups.
        /// </summary>
        internal static string showGroupsCheck {
            get {
                return ResourceManager.GetString("showGroupsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Large Images.
        /// </summary>
        internal static string showLargeImagesCheck {
            get {
                return ResourceManager.GetString("showLargeImagesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string startBtn {
            get {
                return ResourceManager.GetString("startBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Elapsed:.
        /// </summary>
        internal static string timeStatusLabel {
            get {
                return ResourceManager.GetString("timeStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}/{1}.
        /// </summary>
        internal static string titleStatus {
            get {
                return ResourceManager.GetString("titleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom transfer directory can not be on the same storage device as the suite..
        /// </summary>
        internal static string TransferDirMsg {
            get {
                return ResourceManager.GetString("TransferDirMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Path.
        /// </summary>
        internal static string transferGroupBox {
            get {
                return ResourceManager.GetString("transferGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        internal static string urlStatusLabel {
            get {
                return ResourceManager.GetString("urlStatusLabel", resourceCulture);
            }
        }
    }
}
