//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diagonal_pattern {
            get {
                object obj = ResourceManager.GetObject("diagonal_pattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LongName]
        ///Default=*Default
        ///English=*English
        ///EnglishGB=English (British)
        ///Multilingual=*Multilingual
        ///Portuguese=Portuguese (Portugal)
        ///PortugueseBR=Portuguese (Brazilian)
        ///SerbianLatin=Serbian (Latin)
        ///SimpChinese=Chinese (Simplified)
        ///Spanish=Spanish (Spain)
        ///SpanishInternational=Spanish (International)
        ///TradChinese=Chinese (Traditional)
        ///[ShortName]
        ///*Default=Default
        ///*English=English
        ///*Multilingual=Multilingual
        ///Chinese (Simplified)=SimpChinese
        ///Chinese (Traditional)=TradChinese
        ///English (British)=En [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LangNames {
            get {
                return ResourceManager.GetString("LangNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrikaans
        ///Albanian
        ///Arabic
        ///Armenian
        ///Basque
        ///Belarusian
        ///Bulgarian
        ///Catalan
        ///Croatian
        ///Czech
        ///Danish
        ///Dutch
        ///EnglishGB
        ///Estonian
        ///Farsi
        ///Filipino
        ///Finnish
        ///French
        ///Galician
        ///German
        ///Greek
        ///Hebrew
        ///Hungarian
        ///Indonesian
        ///Irish
        ///Italian
        ///Japanese
        ///Korean
        ///Latvian
        ///Lithuanian
        ///Luxembourgish
        ///Macedonian
        ///Malay
        ///Norwegian
        ///Polish
        ///Portuguese
        ///PortugueseBR
        ///Romanian
        ///Russian
        ///Serbian
        ///SerbianLatin
        ///SimpChinese
        ///Slovak
        ///Slovenian
        ///Spanish
        ///SpanishInternational
        ///Sundanese
        ///Swedish
        ///Thai
        ///TradChinese
        ///Turkish
        ///Ukr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo164px {
            get {
                object obj = ResourceManager.GetObject("Logo164px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NsisData {
            get {
                object obj = ResourceManager.GetObject("NsisData", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
